feat: working register

diff --git a/.github/workflows/bater_ponto.yml b/.github/workflows/bater_ponto.yml
--- a/.github/workflows/bater_ponto.yml
+++ b/.github/workflows/bater_ponto.yml
@@ -10,6 +10,9 @@ on:
 jobs:
   run-script:
     runs-on: ubuntu-latest
+    
+    permissions:
+      contents: read
 
     steps:
       - name: Checkout repository
@@ -18,20 +21,34 @@ jobs:
       - name: Set up Python
         uses: actions/setup-python@v2
         with:
-          python-version: '3.x'
+          python-version: '3.9'  # Versão específica do Python para evitar problemas de compatibilidade
+
+      - name: Cache Poetry
+        uses: actions/cache@v2
+        with:
+          path: ~/.cache/pypoetry
+          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
+          restore-keys: |
+            ${{ runner.os }}-poetry-
 
       - name: Install Poetry
         run: |
-          curl -sSL https://install.python-poetry.org | python3 -  # Instala o Poetry
-          echo "export PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV  # Adiciona o Poetry ao PATH para todo o job
-          source $GITHUB_ENV  # Carrega as variáveis de ambiente
+          curl -sSL https://install.python-poetry.org | python3 - 
         shell: bash
 
       - name: Verify Poetry installation
-        run: ~/.local/bin/poetry --version  # Verifica se o Poetry foi instalado corretamente
+        run: poetry --version
+
+      - name: Cache Python packages
+        uses: actions/cache@v2
+        with:
+          path: .venv
+          key: ${{ runner.os }}-poetry-venv-${{ hashFiles('**/poetry.lock') }}
+          restore-keys: |
+            ${{ runner.os }}-poetry-venv-
 
       - name: Install dependencies
-        run: ~/.local/bin/poetry install  # Instala as dependências listadas no pyproject.toml
+        run: poetry install  
 
       - name: Install Google Chrome
         run: |
@@ -41,12 +58,18 @@ jobs:
 
       - name: Install ChromeDriver (latest stable version)
         run: |
-          # Obtém a última versão estável do ChromeDriver
           LATEST_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
           wget -N https://chromedriver.storage.googleapis.com/$LATEST_VERSION/chromedriver_linux64.zip
           unzip chromedriver_linux64.zip
           sudo mv chromedriver /usr/local/bin/chromedriver
           sudo chmod +x /usr/local/bin/chromedriver
 
+      - name: Check script file
+        run: |
+          if [ ! -f scripts/script.py ]; then
+            echo "script.py not found!"
+            exit 1
+          fi
+
       - name: Run Python script with WebDriver Manager
-        run: ~/.local/bin/poetry run python scripts/script.py  # Executa o script Python com o WebDriver Manager
+        run: python3 scripts/script.py
